"use client"

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { TrendingUp, Users, Award, Target, Star, Quote, Briefcase, DollarSign } from "lucide-react"

const stats = [
  {
    icon: Users,
    value: "200+",
    label: "Entrepreneurs Trained",
    description: "Successfully completed our program",
    color: "bg-blue-100 text-blue-600",
  },
  {
    icon: TrendingUp,
    value: "85%",
    label: "Business Success Rate",
    description: "Businesses still operating after 2 years",
    color: "bg-green-100 text-green-600",
  },
  {
    icon: DollarSign,
    value: "₹50L+",
    label: "Average Revenue",
    description: "Generated by successful businesses",
    color: "bg-orange-100 text-orange-600",
  },
  {
    icon: Briefcase,
    value: "150+",
    label: "Jobs Created",
    description: "Employment opportunities generated",
    color: "bg-purple-100 text-purple-600",
  },
]

const successStories = [
  {
    name: "Priya Sharma",
    business: "Organic Food Products",
    location: "Village Rampur",
    image: "/placeholder.svg?height=80&width=80",
    story:
      "Started with ₹50,000 investment, now running a ₹25 lakh annual revenue business supplying organic products to 5 cities.",
    revenue: "₹25L Annual Revenue",
    employees: "12 Employees",
    rating: 5,
  },
  {
    name: "Rajesh Kumar",
    business: "Tech Solutions Startup",
    location: "Sultanpur",
    image: "/placeholder.svg?height=80&width=80",
    story:
      "Developed a mobile app for farmers that now serves 10,000+ users across 3 states. Featured in national media.",
    revenue: "₹40L Annual Revenue",
    employees: "8 Employees",
    rating: 5,
  },
  {
    name: "Meera Patel",
    business: "Handicrafts Export",
    location: "Village Khairabad",
    image: "/placeholder.svg?height=80&width=80",
    story: "Transformed traditional handicrafts into an export business, now supplying to 15 countries worldwide.",
    revenue: "₹15L Annual Revenue",
    employees: "25 Employees",
    rating: 5,
  },
]

const achievements = [
  {
    title: "Best Entrepreneurship Program 2023",
    organization: "National Skill Development Corporation",
    year: "2023",
    description: "Recognized for innovative training methods and outstanding results in rural entrepreneurship",
  },
  {
    title: "Government of India Recognition",
    organization: "Ministry of Skill Development",
    year: "2023",
    description: "Official recognition for contribution to rural economic development",
  },
  {
    title: "MSME Excellence Award",
    organization: "Ministry of MSME",
    year: "2022",
    description: "Excellence in promoting micro, small and medium enterprises",
  },
  {
    title: "Social Impact Award",
    organization: "Rural Development Foundation",
    year: "2022",
    description: "Outstanding contribution to rural community development through entrepreneurship",
  },
]

const alumniNetwork = [
  {
    title: "Active Community",
    description: "200+ entrepreneurs in our alumni network",
    icon: Users,
  },
  {
    title: "Monthly Events",
    description: "Regular networking and knowledge sharing sessions",
    icon: Target,
  },
  {
    title: "Mentorship",
    description: "Alumni mentoring new batch participants",
    icon: Award,
  },
  {
    title: "Business Collaboration",
    description: "Platform for business partnerships and collaborations",
    icon: Briefcase,
  },
]

export function UdyamitaSuccess() {
  return (
    <section className="py-16 sm:py-20 lg:py-24 bg-gray-50">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Impact Statistics */}
        <div className="text-center mb-16">
          <h2 className="text-3xl sm:text-4xl font-bold text-gray-900 mb-4">
            Transforming Lives Through Entrepreneurship
          </h2>
          <p className="text-lg sm:text-xl text-gray-600 max-w-3xl mx-auto">
            Our Udyamita program has created measurable impact in rural communities, empowering individuals to become
            successful entrepreneurs and job creators.
          </p>
        </div>

        <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-6 mb-16">
          {stats.map((stat, index) => {
            const IconComponent = stat.icon
            return (
              <Card key={index} className="text-center hover:shadow-lg transition-all duration-300 border-0 shadow-md">
                <CardHeader className="space-y-4">
                  <div className={`w-16 h-16 mx-auto rounded-full ${stat.color} flex items-center justify-center`}>
                    <IconComponent className="h-8 w-8" />
                  </div>
                  <div>
                    <div className="text-3xl sm:text-4xl font-bold text-gray-900 mb-1">{stat.value}</div>
                    <CardTitle className="text-lg mb-2">{stat.label}</CardTitle>
                    <p className="text-sm text-gray-600">{stat.description}</p>
                  </div>
                </CardHeader>
              </Card>
            )
          })}
        </div>

        {/* Success Stories */}
        <div className="mb-16">
          <div className="text-center mb-12">
            <h3 className="text-2xl sm:text-3xl font-bold text-gray-900 mb-4">Success Stories</h3>
            <p className="text-lg text-gray-600">
              Real entrepreneurs, real businesses - hear from those who transformed their lives
            </p>
          </div>

          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6 lg:gap-8">
            {successStories.map((story, index) => (
              <Card key={index} className="hover:shadow-lg transition-all duration-300">
                <CardHeader>
                  <div className="flex items-start space-x-4">
                    <img
                      src={story.image || "/placeholder.svg"}
                      alt={story.name}
                      className="w-12 h-12 rounded-full object-cover"
                    />
                    <div className="flex-1">
                      <div className="flex items-center justify-between">
                        <div>
                          <h4 className="font-semibold text-gray-900">{story.name}</h4>
                          <p className="text-sm text-gray-600">{story.location}</p>
                        </div>
                        <Badge variant="secondary" className="text-xs">
                          {story.business}
                        </Badge>
                      </div>
                      <div className="flex items-center mt-2">
                        {[...Array(story.rating)].map((_, i) => (
                          <Star key={i} className="h-4 w-4 text-yellow-400 fill-current" />
                        ))}
                      </div>
                    </div>
                  </div>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div className="relative">
                    <Quote className="h-6 w-6 text-gray-300 absolute -top-2 -left-1" />
                    <p className="text-gray-700 italic pl-6 leading-relaxed">{story.story}</p>
                  </div>
                  <div className="grid grid-cols-2 gap-2">
                    <div className="bg-green-50 p-3 rounded-lg">
                      <div className="text-xs font-medium text-green-800">{story.revenue}</div>
                    </div>
                    <div className="bg-blue-50 p-3 rounded-lg">
                      <div className="text-xs font-medium text-blue-800">{story.employees}</div>
                    </div>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>

        {/* Awards and Recognition */}
        <div className="mb-16">
          <div className="text-center mb-12">
            <h3 className="text-2xl sm:text-3xl font-bold text-gray-900 mb-4">Awards & Recognition</h3>
            <p className="text-lg text-gray-600">
              Our commitment to excellence has been recognized by leading organizations
            </p>
          </div>

          <div className="grid md:grid-cols-2 gap-6">
            {achievements.map((achievement, index) => (
              <Card key={index} className="hover:shadow-lg transition-all duration-300">
                <CardContent className="p-6">
                  <div className="flex items-start space-x-4">
                    <div className="w-12 h-12 bg-yellow-100 rounded-full flex items-center justify-center flex-shrink-0">
                      <Award className="h-6 w-6 text-yellow-600" />
                    </div>
                    <div className="flex-1">
                      <div className="flex items-center gap-3 mb-2">
                        <h4 className="font-semibold text-gray-900">{achievement.title}</h4>
                        <Badge variant="outline" className="text-xs">
                          {achievement.year}
                        </Badge>
                      </div>
                      <p className="text-sm text-gray-600 mb-2">{achievement.organization}</p>
                      <p className="text-sm text-gray-700">{achievement.description}</p>
                    </div>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>

        {/* Alumni Network */}
        <div className="mb-16">
          <div className="text-center mb-12">
            <h3 className="text-2xl sm:text-3xl font-bold text-gray-900 mb-4">Alumni Network</h3>
            <p className="text-lg text-gray-600">Join a thriving community of successful entrepreneurs</p>
          </div>

          <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-6">
            {alumniNetwork.map((item, index) => {
              const IconComponent = item.icon
              return (
                <Card key={index} className="text-center hover:shadow-lg transition-all duration-300">
                  <CardContent className="p-6">
                    <div className="w-12 h-12 bg-orange-100 rounded-full flex items-center justify-center mx-auto mb-4">
                      <IconComponent className="h-6 w-6 text-orange-600" />
                    </div>
                    <h4 className="font-semibold text-gray-900 mb-2">{item.title}</h4>
                    <p className="text-sm text-gray-600">{item.description}</p>
                  </CardContent>
                </Card>
              )
            })}
          </div>
        </div>

        {/* Call to Action */}
        <div className="text-center">
          <Card className="max-w-2xl mx-auto bg-gradient-to-r from-orange-600 to-red-600 text-white border-0">
            <CardContent className="p-8">
              <TrendingUp className="w-12 h-12 mx-auto mb-4 opacity-90" />
              <h3 className="text-2xl font-bold mb-4">Ready to Join Our Success Story?</h3>
              <p className="mb-6 opacity-90">
                Take the first step towards building your own successful business and creating impact in your community.
              </p>
              <div className="flex flex-col sm:flex-row gap-4 justify-center">
                <Button size="lg" variant="secondary" className="bg-white text-orange-600 hover:bg-gray-100">
                  Apply for Next Batch
                </Button>
                <Button
                  size="lg"
                  variant="outline"
                  className="border-white text-white hover:bg-white hover:text-orange-600"
                >
                  Connect with Alumni
                </Button>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </section>
  )
}
